/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jOptionPone;

import javax.swing.JOptionPane;

public class App {

    public static void main(String[] args) {
        String username = JOptionPane.showInputDialog("Enter your username:");
        System.out.println(username);
    }
}
