/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jOptionPone;

import javax.swing.JOptionPane;

public class App {

    public static void main(String[] args) {
        String username = JOptionPane.showInputDialog("Enter your username:");
        int age = Integer.parseInt(JOptionPane.showInputDialog("Enter your passsword"));
        JOptionPane.showMessageDialog(null, "Hi, " + username + ". Your age is " + age + ".\nThanks for participation");
    }
}
